site_name: AnatoQuizUp
site_description: AnatoQuizUp é uma plataforma gameficada para aprendizado de anatomia radiológica e de casos clínicos.

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
  palette:
  - scheme: default
    primary: blue
    accent: teal
  - scheme: slate
    primary: blue
    accent: teal

nav:
  - Início: index.md

  - Produto:
    - Visão do Produto: produto/visao.md
    - Lean Inception: produto/lean_inception.md
    - Plano de Gerenciamento de Custos: produto/plano-de-custos.md

  - Contribuição:
    - Política de Branches: contribuicao/branches.md
    - Política de Commits: contribuicao/commits.md
    - Política de Pull Requests: contribuicao/pull_requests.md
    - Política de Issues: contribuicao/issues.md
  
  - Reuniões:
    - Template de ata de reunião: reunioes/modelo-ata-reuniao.md 

extra_css:
  - stylesheets/extra.css
