site_name: AnatoQuizUp
site_description: AnatoQuizUp é uma plataforma gameficada para aprendizado de anatomia radiológica e de casos clínicos.

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
  palette:
  - scheme: default
    primary: blue
    accent: teal
  - scheme: slate
    primary: blue
    accent: teal

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Início: index.md

  - Produto:
    - Visão do Produto: produto/visao.md
    - Lean Inception: produto/lean_inception.md
    - EAP: produto/EAP.md
    - Plano de Gerenciamento de Custos: produto/plano-de-custos.md
    - Plano de Gerenciamento de Riscos: produto/plano-de-riscos.md
    - Roadmap: produto/roadmap.md
    - Backlog:
      - Visão Geral: backlog/visao-geral.md
      - Release Major 1: backlog/release-major-1.md

  - Arquitetura:
    - Visão Geral: arquitetura/visao-geral.md
    - Tecnologias: arquitetura/tecnologias.md
    - Decisões Arquiteturais: arquitetura/decisoes.md
    - Banco de Dados: arquitetura/banco-de-dados.md
    - Endpoints: arquitetura/endpoints.md

  - Gestão:
    - Metodologia: metodologia/metodologia.md
    - Dashboards da R1: dashboards.md
    - Quadro de Conhecimento: metodologia/quadro-conhecimento.md

  - Operação:
    - Ambiente de Homologação: operacao/ambiente-homologacao.md

  - Contribuição:
    - Política de Branches: contribuicao/branches.md
    - Política de Commits: contribuicao/commits.md
    - Política de Pull Requests: contribuicao/pull_requests.md
    - Política de Issues: contribuicao/issues.md

  - Reuniões:
    - Template de ata de reunião: reunioes/modelo-ata-reuniao.md

extra_css:
  - stylesheets/extra.css
